name: Terraform Pipeline

on:
  push:
    branches:
      - main
      - infra
    paths:
      - "infra/terraform/**"
      - ".github/workflows/terraform.yml"

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false

jobs:

  terraform-plan:
    name: 📋 Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var-file="terraform.ci.tfvars" \
            -lock-timeout=5m


  terraform-apply:
    name: 🚀 Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan

    defaults:
      run:
        working-directory: infra/terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -reconfigure

      #  SAFE STATE SYNC
      - name: Terraform Refresh State (SAFE)
        run: |
          terraform apply -refresh-only -auto-approve \
            -var-file="terraform.ci.tfvars"

      # APPLY INFRASTRUCTURE
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var-file="terraform.ci.tfvars"